# inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 30

Naming/ClassAndModuleCamelCase:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/AsciiComments:
  Enabled: false
