# Problem #2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

require "test/unit"



class TestProblem_2 < Test::Unit::TestCase
	def find_sum_of_even_values_fibonacci_terms
		last = 1
		prev = sum = 0

		while last < 4000000
		  temp = last
		  last += prev
		  prev = temp

		  sum += last if last % 2 == 0
		end	
		sum
	end

	def test_sum_of_even_valued_fibonacci_terms
		sum = find_sum_of_even_values_fibonacci_terms
		assert_equal 4613732, sum
	end
end