# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

require 'test/unit'
require_relative 'tools/numbers'

class TestProblem_12 < Test::Unit::TestCase

	def triangle_numbers(count)
	  triangles = [1]
	  (2..count).each do |i|
	    triangles << i**2 - triangles[i-2]
	  end
	  triangles
	end

	def test_first_triangle_number_that_have_over_five_hundred_divisors
		triangles = triangle_numbers(10**5)
		primes = eratosthenes 10**6

		triangle = triangles.find { |value| value > 10**6 and value.divisors_count(primes) > 500 }
		assert_equal(76576500, triangle)
	end
end




