# Consider all integer combinations of ab for 2  a  5 and 2  b  5:
#
# 22=4, 23=8, 24=16, 25=32
# 32=9, 33=27, 34=81, 35=243
# 42=16, 43=64, 44=256, 45=1024
# 52=25, 53=125, 54=625, 55=3125
# If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
# 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

# How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?

require 'set'
require "test/unit"

class Test_Problem29 < Test::Unit::TestCase
	def powers_combinations(a_limit, b_limit)
		powers = Set.new	
		(2..a_limit).each do |a|
			(2..b_limit).each do |b|
				powers << a ** b
				powers << b ** a
			end
		end
		powers
	end

	def test_different_powers_combinations_of_5
		assert_equal 15, powers_combinations(5,5).count
	end

	def test_different_powers_combinations_of_100
		assert_equal 9183, powers_combinations(100,100).count
	end
end